import { CoinbaseWallet } from '@web3-react/coinbase-wallet'
import { GnosisSafe } from '@web3-react/gnosis-safe'
import { MetaMask } from '@web3-react/metamask'
import { Network } from '@web3-react/network'
import type { Connector } from '@web3-react/types'
import { WalletConnect as WalletConnect } from '@web3-react/walletconnect'
import { WalletConnect as WalletConnectV2 } from '@web3-react/walletconnect-v2'
import { BitKeep } from '@akkafinance/web3-react-bitkeep'
import { SafePal } from '@akkafinance/web3-react-safepal'
import { MathWallet } from '@akkafinance/web3-react-mathwallet'

export function getName(connector: Connector) {
  if (connector instanceof MetaMask) return 'MetaMask'
  if (connector instanceof WalletConnectV2) return 'WalletConnect V2'
  if (connector instanceof WalletConnect) return 'WalletConnect'
  if (connector instanceof CoinbaseWallet) return 'Coinbase Wallet'
  if (connector instanceof Network) return 'Network'
  if (connector instanceof GnosisSafe) return 'Gnosis Safe'
  if (connector instanceof BitKeep) return 'BitKeep'
  if (connector instanceof SafePal) return 'SafePal'
  if (connector instanceof MathWallet) return 'MathWallet'
  return 'Unknown'
}
